### ISSUE TITLE
error: elm-app-gen-create(1) does not exist, try --help

### ISSUE THREAD

**Issue by martindlarsson** [MattCheely/elm-app-gen#18]
The text below speaks for itself i think:
`success Installed "elm-app-gen@0.0.3" with binaries:
      - elm-app-gen
✨  Done in 8.46s.
Martins-MBP:kmti-admin martin$ elm-app-gen  
error: elm-app-gen-create(1) does not exist, try --help
Martins-MBP:kmti-admin martin$ elm-app-gen --help
Usage: elm-app-gen [options] [command]

Options:
  -V, --version  output the version number
  -h, --help     output usage information

Commands:
  create         Creates a new application
  help [cmd]     display help for [cmd]
Martins-MBP:kmti-admin martin$ elm-app-gen create
error: elm-app-gen-create(1) does not exist, try --help
Martins-MBP:kmti-admin martin$ elm-app-gen create testapp
error: elm-app-gen-create(1) does not exist, try --help
Martins-MBP:kmti-admin martin$ elm-app-gen help create
error: elm-app-gen-create(1) does not exist, try --help
Martins-MBP:kmti-admin martin$ elm-app-gen -V
0.0.3
`

**Comment by MattCheely** [comment]
Oh, that's interesting. It works fine installed with npm but fails with yarn. Only difference I see is the number of symlinks on my machine between the entry in `$PATH` and the actual file location.  I'll try to get a fix out for this shortly. 

Also, I'm surprised someone found this project! Sorry it's broken for you!

**Comment by MattCheely** [comment]
Hmm. Looks like this is an issue in commander, so I can't fix it directly. There is an open PR currently under review: https://github.com/tj/commander.js/pull/869/files

I will keep an eye on that and see if can push it along a bit if it does not update soon.  Maybe in the meantime you can install with `npm`?

**Comment by martindlarsson** [comment]
Thanks npm worked fine!

I found your package through a user on the elm slack. He had used your
yoman generator before.

Den mån 4 feb. 2019 03:19Matthew Cheely <notifications@github.com> skrev:

**Comment by MattCheely** [comment]
Commander has published a new version including: https://github.com/tj/commander.js/pull/935, so this should be working again.
