### ISSUE TITLE
Built apps do not work when placed in subdirectories

### ISSUE THREAD

**Issue by remmah** [MattCheely/elm-app-gen#22]
When building the default Gutenberg app via `npm run build`, the `src` URL for `app.js` in `index.html` gets changed to a root-relative URL:

``` html
<script src="/app.2f08bf58.js"></script>
             ^
```

The leading slash gets added even if the URL in the source file does not have one. This leads to the js file not being found if the built app is placed in a subdirectory (e.g. GitHub Pages), as the browser looks for the js file in the root level of the domain, rather than the subdirectory where `index.html` is.

Removing the `/` from the `src` URL in the generated `index.html` fixes the issue.

**Comment by MattCheely** [comment]
Thanks for calling attention to this! Luckily, there is a fix for this in the latest release, which should work for new projects after updating the global elm-app-gen install.  

For existing apps, the solution is to update the `build` script in `package.json`.  You can see the new version here: https://github.com/MattCheely/elm-app-gen/blob/master/generators/app/templates/parcel/package.json#L9

The important part was changing 
`parcel build src/index.html` 
to
`parcel build src/index.html --public-url ./`

**Comment by remmah** [comment]
Thanks! I made that edit to `package.json` and everything's working again!
