### ISSUE TITLE
Upgrade to Elm 0.19.1

### ISSUE THREAD

**Issue by jesse-c** [MattCheely/elm-app-gen#27]
It's out! 🎉

**Comment by bigardone** [comment]
Would this be good enough?

https://github.com/MattCheely/elm-app-gen/pull/28

**Comment by MattCheely** [comment]
That PR looks good to me. I will run some checks over the holiday weekend and get it merged and publish a new version. Sorry about the delayed follow-up on this, I've had a lot going on outside of the coding world lately, and I am overdue on a number of open-source project follow-ups.

**Comment by MattCheely** [comment]
Fixed in #28 and published as 1.3.0
