### ISSUE TITLE
Create generator for localstorage ports

### ISSUE THREAD

**Issue by MattCheely** [MattCheely/elm-app-gen#9]
Ports are often tricky to get used to for folks new to Elm or unfamiliar with the actor model of communication. The localStorage API is a common use case for ports, so generating some nice binding for folks could be helpful to them in getting up and running with localStorage and in seeing an example of how to work with ports well.

**Comment by kalutheo** [comment]
We can add that once #8 is ready on the document app for instance .
Moreover we could add a FAQ on the readme.md to point people on the right app  for a given use case ( ex : how can I use local storage with Elm ? Etc..)

**Comment by MattCheely** [comment]
I'm going to skip this one for now, actually.
